openapi: 3.0.3
info:
  title: STD23051 - TD_Final - Management of Football's Competition
  description: It's an API for managing football competitions, teams, and players.
  version: 1.0.0
servers:
  - url: https://localhost.std23051.com

components:
  schemas:
    Competition:
      type: object
      properties:
        name:
          type: string
          example: LIGA
        location:
          type: string
          example: SPAIN

    Team:
      type: object
      properties:
        name:
          type: string
          example: Fc Barcelona
        slogan:
          type: string
          example: "Visca el Barça"
        competitions:
          type: array
          items:
            $ref: '#/components/schemas/Competition'
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'

    Player:
      type: object
      properties:
        name:
          type: string
          example: Lamine Yamal
        number:
          type: integer
          example: 19
        strongFoot:
          type: string
          enum: [Left, Right]
          example: Left

  parameters:
    TeamNameQuery:
      in: query
      name: TeamNames
      schema:
        type: string
      description: Filter the list of club by name

    PlayerNameQuery:
      in: query
      name: PlayerNames
      schema:
        type: string
      description: Filter the list of players by name

    PaginationParams:
      in: query
      name: page
      schema:
        type: integer
      required: true
      description: Page number for pagination

    PageSizeParams:
      in: query
      name: pageSize
      schema:
        type: integer
      required: true
      description: Number of items per page

paths:
  /competitions:
    get:
      summary: Get competitions' list
      parameters:
        - $ref: '#/components/parameters/PaginationParams'
        - $ref: '#/components/parameters/PageSizeParams'
      responses:
        '200':
          description: List of competitions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Competition'
    post:
      summary: Create new competition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Competition'
      responses:
        '201':
          description: Competition created successfully!!!

  /teams:
    get:
      summary: Get a list of teams
      parameters:
        - $ref: '#/components/parameters/TeamNameQuery'
        - $ref: '#/components/parameters/PaginationParams'
        - $ref: '#/components/parameters/PageSizeParams'
      responses:
        '200':
          description: A list of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
    post:
      summary: Create new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '201':
          description: Team created

  /teams/{teamId}/players:
    parameters:
      - name: teamId
        in: path
        required: true
        schema:
          type: string
        description: ID of the team
    get:
      summary: Get list of players for a specific team
      parameters:
        - $ref: '#/components/parameters/PlayerNameQuery'
        - $ref: '#/components/parameters/PaginationParams'
        - $ref: '#/components/parameters/PageSizeParams'
      responses:
        '200':
          description: A list of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
    post:
      summary: Create new player in a specific team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Player'
      responses:
        '201':
          description: Player created successfully!!!

  /teams/{teamId}/competitions:
    post:
      summary: Associate a team to a competitions
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: string
          description: ID of the team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Competition'
      responses:
        '200':
          description: Competitions associated with the team successfully!!!

  /teams/{teamId}/players/transfer:
    post:
      summary: Transfer a list of players to a specific team
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: string
          description: ID of the team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Player'
      responses:
        '200':
          description: Players transferred to the team successfully!!!